### ISSUE TITLE
Import both CONFIRMED and UNCONFIRMED account statuses

### ISSUE THREAD

**Issue by caiconkhicon** [aws-solutions/cognito-user-profiles-export-reference-architecture#9] opened 2021-03-22 13:08 UTC
**Is your feature request related to a problem? Please describe.**
When I run the import StepFunction, it fails because the Lambda function cannot import users with the account status `UNCONFIRMED`. The failing step is `Parallel: CheckUserImportJob`. Its log looks like this:
```
        "ImportedUsers": 14,
        "SkippedUsers": 0,
        "FailedUsers": 32,
        "CompletionMessage": "Too many users have failed or been skipped during the import."

```

**Describe the feature you'd like**
The Lambda function should be able to import `UNCONFIRMED` users (or ideally, make it a parameter).

**Comment by ericquinones** [comment] 2021-03-25 20:31
Hi @caiconkhicon -
The `CompletionMessage` you see there is generated by Cognito's User Import job ([more info](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-using-import-tool.html)).

For specific information about why the job failed, you will need to review the CloudWatch Logs for that Cognito Import Job. If you go to the CloudWatch console, you should see a log group for your user pool. Something like `/aws/cognito/userpools/<pool id>/<pool name>`

Inside the log group, you should find a Log Stream for the import job and within it, you should see more detailed logs about why each individual user failed to import. If there are unconfirmed users in the pool, it could be because of missing required attributes but the logs should confirm why those users failed to import.

**Comment by caiconkhicon** [comment] 2021-03-31 13:02
@ericquinones : Thanks for your reply. Sorry I forgot replying you. Yes, now I know that. However, now I face another problem, which is with Cognito, but maybe you also can help me. When doing export/import, my user pool had several users with `email_verified=false`, and Cognito denied importing them. The problem is, from what I observe in CloudWatch, when there are users with `email_verified=false`, Cognito stops after the first 50 items (the log always stops at the 51st line). This behaviour blocks me from doing export/import. IMHO Cognito should just ignore these users and continue with others. Do you have any idea how I can overcome this issue?

**Comment by ericquinones** [comment] 2021-04-06 14:23
Hi @caiconkhicon -

As you mentioned, that behavior comes from the Cogntio User Import process itself so there would be nothing we can do on the solution side to have Cognito continue processing users after their limit of failed imports is hit. I found information in the [Cognito documentation](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-using-import-tool-csv-header.html) stating that the destination user pool itself must have at least one auto-verified attribute and the users in the CSV need to have one of the auto-verified attributes set to `true`.

If your issue is limited to unconfirmed users, a workaround might be to sort the CSV file so that users with `email_verified=false` or `phone_number_verified=false` are at the end of the file. This way, the users that are expected to import successfully will be processed first. You can look into creating a custom build of the solution with these changes (please see the README file for how to build the solution from the source code).

The logic for how the solution determines true/false for the auto-verified attributes is [here](https://github.com/awslabs/cognito-user-profiles-export-reference-architecture/blob/0e1390fa560dbb1bacfa53c6265f955f48d5362e/source/workflow-import/import-users.js#L180-L187). And the CSV file is created in [this function](https://github.com/awslabs/cognito-user-profiles-export-reference-architecture/blob/0e1390fa560dbb1bacfa53c6265f955f48d5362e/source/workflow-import/import-users.js#L73-L140). 

Thank you

**Comment by caiconkhicon** [comment] 2021-04-12 15:03
@ericquinones : Thanks a lot for your advise. I will try it and tell you the result later. What do you think if I create an PR here?

**Comment by ericquinones** [comment] 2021-05-21 17:59
Hi @caiconkhicon - 

Apologies for the delay. PRs are okay to submit and we will take a look. We have some guidance [here](https://github.com/awslabs/cognito-user-profiles-export-reference-architecture/blob/master/CONTRIBUTING.md).

Thanks!

**Comment by Warns** [comment] 2022-02-28 23:02
Hi @caiconkhicon, sorry if unrelated but where did you provide the user pool ID to the step function? I basically deleted the users and want to import to the same pool. But I'm failing with the error `Unable to determine the new user pool ID`. Thanks

**Comment by mikeols** [comment] 2023-09-22 18:49
Appears questions have been addressed. Closing.

**Closed by mikeols** 2023-09-22 18:49 UTC
Labels: enhancement
